name: link4launches
description: Aim to the stars.

publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.0.15
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.3.1
  flutter_file_downloader: ^1.1.2
  flutter_svg: ^2.0.7
  permission_handler: ^10.4.3
  http: ^0.13.5
  url_launcher: ^6.1.12
  flutter_launcher_icons: ^0.13.1
  # google_fonts: ^4.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app-icon/app-icon.png"


flutter_native_splash:
  color: '#005B76' # dark blue
  image: 'assets/app-icon/app-icon.png'


flutter:
  uses-material-design: true
  assets:
    - 'assets/snackbar/space_devs_rocket.svg'